### PR TITLE
1.18 port

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
Create a new branch before merging of course...

### CODE REVIEW

**Comment by DragonEggBedrockBreaking** [comment]
I had to remove `tweakAlwaysRenderBarrierParticles`, but other than that everything should work. Note that the versions of masa's mods have stayed the same, but this mod works with the 1.18 versions - the only reason I didn't change the version is because the mods don't have official 1.18 versions with releases - to use them in 1.18 you need the unofficial and unreleased ports made by @valca

**Comment by DragonEggBedrockBreaking** [comment]
Currently fixing some stuff, drafting it to prevent merge while I fix this.

**Comment by DragonEggBedrockBreaking** [comment]
fixed `tweakAlwaysRenderBarrierParticles`

**Comment by hp3721** [comment]
lgtm

**Pull request merged**
