### PR TITLE
Fix compatibility with WeirdAddons

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
This PR contains 3 changes:
- It adds the `value` parameter, which allows the mod to actually build
- Changes priority from 1001 to 999, since lower priority (counter-intuitively) means that it is run first. This is important for an `@Overwrite` from what I understand.
- Sets the `defaultRequire` to 0, otherwise the fix doesn't work

### CODE REVIEW

**Comment by hp3721** [comment]
The goal isn't for the mixin to be applied first. WeirdAddons uses ModifyArg in its mixin into the WorldAccess interface which isn't supported by mixins. For some reason it only causes errors if another mod attempts to mixin into the interface after it. The Overwrite in MasaAdditions is a non-issue since WeirdAddons does not attempt to modify the same method. It would be better to create a PR to WeirdAddons to lower its WorldAccess mixin priority. Though, I have fixed the issue with the prior commit ~~(Last commit was done through Github's web interface)~~.

**Comment by DragonEggBedrockBreaking** [comment]
> Though, I have fixed the issue with the prior commit ~(Last commit was done through Github's web interface)~.

But technically it wasn't fixed. Although the lowering priority was not necessary, the other two parts were. The mod simply does not build without the `value` parameter, and the game simply does not launch without editing the `defaultRequire`.

**Comment by DragonEggBedrockBreaking** [comment]
Nvm, I didn't see the force push

**Comment by DragonEggBedrockBreaking** [comment]
Wait, ignore both of the previous messages... For me it doesn't launch unless you also change `defaultRequire`...

**Comment by hp3721** [comment]
Add me on Discord. I am unable to reproduce this issue. The game launches with both mods functioning without defaultRequire.

**Pull request closed without merging**
